spring:
 application:
   name: ms-renegociacao

server:
  port: 9090

eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8080/eureka
     
messages:
  basename: messages
  default:
    country: BR
    language: PT
    encoding: UTF-8
